import React from "react";
import Head from "next/head";
import Navbar from "../components/navbar";
import HeroSection from "../components/hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lauren Mercer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <HeroSection />
    </div>
  );
}
